# Generated by Django 3.2.3 on 2021-06-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture_Main_Img',
            new_name='imagine',
        ),
    ]
